In [10]:
import cv2
import math
import numpy as np
import sys

def apply_mask(matrix, mask, fill_value):
    #print("MATRIX=", matrix)
    #print("mask=\n" ,mask)
    #print("fill value=\n", fill_value)
                 
    masked = np.ma.array(matrix, mask=mask, fill_value=fill_value)
    print('MASKED=',masked)
    return masked.filled()

def apply_threshold(matrix, low_value=255, high_value=255):
    low_mask = matrix < low_value
    print("low mask=",low_mask)
    
    matrix = apply_mask(matrix, low_mask, low_value)
    print('Low MASK->',low_mask,'\nMatrix->',matrix)

    high_mask = matrix > high_value
    matrix = apply_mask(matrix, high_mask, high_value)

    return matrix

def simplest_cb(img, percent):
    assert img.shape[2] == 3
    assert percent > 0 and percent < 100
    print("shape of image = ", img.shape[2])

    half_percent = percent / 200.0
    print('HALF PERCENT->',half_percent)

    channels = cv2.split(img)
    print('Channels->\n',channels)
    print('Shape->',channels[0].shape)
    print('Shape of channels->',len(channels[2]))

    out_channels = []
    for channel in channels:
        assert len(channel.shape) == 2

	# find the low and high precentile values (based on the input percentile)
        height, width = channel.shape
        vec_size = width * height
        flat = channel.reshape(vec_size)
        print('vec=',vec_size,'\nFlat=',flat)
        assert len(flat.shape) == 1

        flat = np.sort(flat)

        n_cols = flat.shape[0]
        print("Number of columns = ", n_cols)

        low_val  = flat[math.floor(n_cols * half_percent)]
        high_val = flat[math.ceil( n_cols * (1.0 - half_percent))]

        print("Lowval: ", low_val)
        print("Highval: ", high_val)
        print(flat[60])
        print(flat[11940])
        

        # saturate below the low percentile and above the high percentile
        thresholded = apply_threshold(channel, low_val, high_val)
        # scale the channel
        normalized = cv2.normalize(thresholded, thresholded.copy(), 0, 255, cv2.NORM_MINMAX)
        out_channels.append(normalized)

    return cv2.merge(out_channels)

if __name__ == '__main__':
    #img = cv2.imread(sys.argv[1])
    cap=cv2.VideoCapture('/home/dheeraj/Downloads/Barracuda.mp4')
    #img = cv2.imread('/home/dheeraj/Downloads/Whale.mov')
    #cap.set(cv2.cv.CV_CAP_PROP_FPS, 60)
    
    while True:
        ret, frame=cap.read()
        frame_width_fx = 640
        frame_height_fy = 480
        frame = cv2.resize(frame, (frame_width_fx, frame_height_fy))
        

        out = simplest_cb(frame, 1)
        cv2.imshow("Before", frame) 
        cv2.imshow("After", out)
        key=cv2.waitKey(1)
        if key==27:
            break
        
    cap.release()
    cv2.destroyAllWindows()


shape of image =  3
HALF PERCENT-> 0.005
Channels->
 [array([[100, 154, 156, ..., 161, 164,  79],
       [151, 226, 228, ..., 234, 238, 137],
       [158, 234, 236, ..., 235, 239, 137],
       ...,
       [ 91, 132, 140, ..., 154, 155, 101],
       [ 95, 130, 132, ..., 144, 160, 100],
       [ 72, 101, 100, ...,  98, 112,  68]], dtype=uint8), array([[ 82, 135, 134, ...,  98,  98,  53],
       [117, 194, 192, ..., 145, 146,  84],
       [118, 196, 193, ..., 145, 146,  84],
       ...,
       [ 70, 100, 100, ..., 129, 133,  86],
       [ 83, 109, 101, ..., 126, 145,  90],
       [ 70,  89,  78, ...,  87, 103,  66]], dtype=uint8), array([[ 48,  61,  64, ...,  20,  18,  21],
       [ 68, 102, 102, ...,  32,  29,  18],
       [ 63,  96, 100, ...,  32,  29,  18],
       ...,
       [ 49,  67,  66, ...,  90,  93,  50],
       [ 61,  74,  68, ...,  88, 107,  58],
       [ 46,  57,  48, ...,  50,  68,  37]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [100 154 15

Channels->
 [array([[100, 154, 156, ..., 161, 164,  79],
       [151, 226, 228, ..., 234, 238, 137],
       [158, 234, 236, ..., 235, 239, 137],
       ...,
       [ 98, 144, 170, ..., 154, 155, 101],
       [ 91, 135, 146, ..., 144, 160, 100],
       [ 67,  95,  99, ...,  98, 112,  68]], dtype=uint8), array([[ 82, 135, 134, ...,  98,  98,  53],
       [117, 194, 192, ..., 145, 146,  84],
       [118, 196, 193, ..., 145, 146,  84],
       ...,
       [ 58,  93, 112, ..., 129, 133,  86],
       [ 60,  97, 102, ..., 126, 145,  90],
       [ 41,  65,  61, ...,  87, 103,  66]], dtype=uint8), array([[ 48,  61,  64, ...,  20,  18,  21],
       [ 68, 102, 102, ...,  32,  29,  18],
       [ 63,  96, 100, ...,  32,  29,  18],
       ...,
       [ 36,  62,  71, ...,  90,  93,  50],
       [ 36,  65,  64, ...,  88, 107,  58],
       [ 21,  38,  29, ...,  50,  68,  37]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [100 154 156 ...  98 112  68]
Number of columns =  3

 [85 85 93 ... 88 95 85]]
vec= 307200 
Flat= [48 61 64 ... 52 60 37]
Number of columns =  307200
Lowval:  0
Highval:  172
0
2
low mask= [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
MASKED= [[48 61 64 ... 17 15 16]
 [68 102 102 ... 28 25 10]
 [63 96 100 ... 27 24 10]
 ...
 [45 81 79 ... 87 93 47]
 [42 74 83 ... 88 99 57]
 [22 42 49 ... 52 60 37]]
Low MASK-> [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]] 
Matrix-> [[ 48  61  64 ...  17  15  16]
 [ 68 102 102 ...  28  25  10]
 [ 63  96 100 ...  27  24  10]
 ...
 [ 45  81  79 ...  87  93  47]
 [ 42  74  83 ...  

Channels->
 [array([[100, 154, 156, ..., 159, 159,  77],
       [151, 226, 228, ..., 233, 232, 132],
       [158, 234, 236, ..., 233, 233, 133],
       ...,
       [120, 186, 179, ..., 158, 168,  98],
       [110, 167, 174, ..., 148, 154, 100],
       [ 77, 125, 125, ..., 105, 107,  72]], dtype=uint8), array([[ 82, 135, 134, ...,  98,  96,  52],
       [117, 194, 192, ..., 146, 142,  81],
       [118, 196, 193, ..., 146, 142,  81],
       ...,
       [ 96, 154, 151, ..., 125, 137,  75],
       [ 91, 142, 150, ..., 121, 129,  80],
       [ 60, 103, 111, ...,  84,  88,  60]], dtype=uint8), array([[ 48,  61,  64, ...,  17,  15,  16],
       [ 68, 102, 102, ...,  28,  25,  10],
       [ 63,  96, 100, ...,  27,  24,  10],
       ...,
       [ 60,  89,  78, ...,  86,  98,  41],
       [ 56,  85,  86, ...,  85,  93,  50],
       [ 29,  57,  62, ...,  49,  55,  33]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [100 154 156 ... 105 107  72]
Number of columns =  3

 [123 123 123 ... 123 123 123]]
vec= 307200 
Flat= [ 82 135 134 ...  87  98  48]
Number of columns =  307200
Lowval:  86
Highval:  246
71
121
low mask= [[ True False False ... False False  True]
 [False False False ... False False  True]
 [False False False ... False False  True]
 ...
 [False False False ... False False  True]
 [False False False ... False False  True]
 [ True False False ... False False  True]]
MASKED= [[-- 135 134 ... 96 93 --]
 [117 194 192 ... 142 140 --]
 [118 196 193 ... 142 139 --]
 ...
 [93 151 137 ... 138 143 --]
 [87 146 135 ... 132 141 --]
 [-- 94 94 ... 87 98 --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False  True]
 [False False False ... False False  True]
 ...
 [False False False ... False False  True]
 [False False False ... False False  True]
 [ True False False ... False False  True]] 
Matrix-> [[ 86 135 134 ...  96  93  86]
 [117 194 192 ... 142 140  86]
 [118 196 193 ... 142 139  86]
 ...
 [ 93 151 137 ...

Number of columns =  307200
Lowval:  1
Highval:  168
0
2
low mask= [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
MASKED= [[44 61 64 ... 15 14 16]
 [65 102 102 ... 25 23 11]
 [60 96 100 ... 25 22 12]
 ...
 [57 69 73 ... 98 108 70]
 [57 57 57 ... 97 106 68]
 [37 34 38 ... 58 57 32]]
Low MASK-> [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]] 
Matrix-> [[ 44  61  64 ...  15  14  16]
 [ 65 102 102 ...  25  23  11]
 [ 60  96 100 ...  25  22  12]
 ...
 [ 57  69  73 ...  98 108  70]
 [ 57  57  57 ...  97 106  68]
 [ 37  34  38 ...  58  57  32]]
MASKED= [[44 61 64 ... 

shape of image =  3
HALF PERCENT-> 0.005
Channels->
 [array([[ 91, 156, 156, ..., 161, 162,  83],
       [147, 232, 232, ..., 233, 233, 141],
       [147, 234, 236, ..., 233, 232, 140],
       ...,
       [125, 203, 200, ..., 166, 176,  90],
       [128, 201, 195, ..., 158, 162,  89],
       [ 86, 135, 121, ..., 101, 105,  61]], dtype=uint8), array([[ 80, 133, 130, ...,  96,  94,  56],
       [116, 191, 191, ..., 142, 139,  86],
       [115, 193, 191, ..., 142, 138,  83],
       ...,
       [107, 170, 161, ..., 151, 147,  81],
       [108, 167, 155, ..., 144, 141,  80],
       [ 67, 109,  95, ...,  92,  92,  55]], dtype=uint8), array([[ 45,  66,  71, ...,  18,  17,  20],
       [ 65, 101, 102, ...,  28,  27,  18],
       [ 64,  98, 102, ...,  25,  24,  18],
       ...,
       [ 65,  94,  93, ..., 102,  97,  51],
       [ 64,  99,  96, ...,  95,  93,  50],
       [ 41,  69,  61, ...,  57,  54,  38]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [ 91 156 15

Number of columns =  307200
Lowval:  90
Highval:  245
70
121
low mask= [[ True False False ... False False  True]
 [False False False ... False False  True]
 [False False False ... False False  True]
 ...
 [False False False ... False False False]
 [False False False ... False False  True]
 [ True False False ... False False  True]]
MASKED= [[-- 133 130 ... 96 95 --]
 [116 191 191 ... 143 139 --]
 [115 193 191 ... 143 138 --]
 ...
 [97 168 167 ... 139 152 97]
 [104 163 158 ... 156 150 --]
 [-- 105 104 ... 103 97 --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False  True]
 [False False False ... False False  True]
 ...
 [False False False ... False False False]
 [False False False ... False False  True]
 [ True False False ... False False  True]] 
Matrix-> [[ 90 133 130 ...  96  95  90]
 [116 191 191 ... 143 139  90]
 [115 193 191 ... 143 138  90]
 ...
 [ 97 168 167 ... 139 152  97]
 [104 163 158 ... 156 150  90]
 [ 90 105 104 ... 103  97  90]]


Number of columns =  307200
Lowval:  0
Highval:  162
0
2
low mask= [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
MASKED= [[45 66 71 ... 20 18 20]
 [65 101 103 ... 30 28 18]
 [64 98 102 ... 26 24 18]
 ...
 [58 95 98 ... 77 98 62]
 [58 97 100 ... 90 99 62]
 [39 61 68 ... 68 59 35]]
Low MASK-> [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]] 
Matrix-> [[ 45  66  71 ...  20  18  20]
 [ 65 101 103 ...  30  28  18]
 [ 64  98 102 ...  26  24  18]
 ...
 [ 58  95  98 ...  77  98  62]
 [ 58  97 100 ...  90  99  62]
 [ 39  61  68 ...  68  59  35]]
MASKED= [[45 66 71 ... 2

       [ 42,  66,  58, ...,  57,  60,  38]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [ 91 156 156 ... 109 121  71]
Number of columns =  307200
Lowval:  127
Highval:  242
106
187
low mask= [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True False False ... False False  True]
 [ True False False ... False False  True]
 [ True False  True ...  True  True  True]]
MASKED= [[-- 156 156 ... 161 161 --]
 [147 232 233 ... 233 232 139]
 [147 234 236 ... 233 230 139]
 ...
 [-- 196 194 ... 181 194 --]
 [-- 192 188 ... 162 182 --]
 [-- 132 -- ... -- -- --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True False False ... False False  True]
 [ True False False ... False False  True]
 [ True False  True ...  True  True  True]] 
Matrix-> [[127 156 156 ... 161 161 127]
 [147 2

Number of columns =  307200
Lowval:  91
Highval:  243
70
121
low mask= [[ True False False ... False False  True]
 [False False False ... False False  True]
 [False False False ... False False  True]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [ True False  True ... False False  True]]
MASKED= [[-- 133 129 ... 96 97 --]
 [116 191 192 ... 142 141 --]
 [115 193 191 ... 142 140 --]
 ...
 [94 151 155 ... 175 174 109]
 [94 156 152 ... 163 159 96]
 [-- 96 -- ... 103 101 --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False  True]
 [False False False ... False False  True]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [ True False  True ... False False  True]] 
Matrix-> [[ 91 133 129 ...  96  97  91]
 [116 191 192 ... 142 141  91]
 [115 193 191 ... 142 140  91]
 ...
 [ 94 151 155 ... 175 174 109]
 [ 94 156 152 ... 163 159  96]
 [ 91  96  91 ... 103 101  91]]
M

shape of image =  3
HALF PERCENT-> 0.005
Channels->
 [array([[ 91, 156, 158, ..., 157, 157,  85],
       [147, 232, 235, ..., 236, 231, 135],
       [147, 234, 236, ..., 238, 231, 133],
       ...,
       [121, 197, 184, ..., 204, 218, 131],
       [115, 198, 189, ..., 202, 208, 130],
       [ 81, 125, 123, ..., 135, 141,  85]], dtype=uint8), array([[ 80, 133, 129, ...,  99,  99,  55],
       [116, 191, 192, ..., 145, 144,  87],
       [115, 193, 191, ..., 142, 142,  86],
       ...,
       [102, 163, 151, ..., 175, 182, 108],
       [ 98, 164, 149, ..., 173, 172, 106],
       [ 65, 100,  94, ..., 113, 112,  66]], dtype=uint8), array([[ 45,  66,  71, ...,  20,  20,  20],
       [ 65, 101, 103, ...,  31,  31,  18],
       [ 64,  98, 102, ...,  26,  26,  19],
       ...,
       [ 66,  94,  85, ...,  98, 102,  58],
       [ 58, 102,  90, ..., 101, 100,  62],
       [ 41,  64,  65, ...,  63,  62,  45]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [ 91 156 15

Number of columns =  307200
Lowval:  0
Highval:  159
0
2
low mask= [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
MASKED= [[45 66 71 ... 20 20 20]
 [65 101 103 ... 31 31 18]
 [64 98 102 ... 26 26 19]
 ...
 [63 90 90 ... 96 90 54]
 [55 85 87 ... 95 92 59]
 [37 59 61 ... 63 63 41]]
Low MASK-> [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]] 
Matrix-> [[ 45  66  71 ...  20  20  20]
 [ 65 101 103 ...  31  31  18]
 [ 64  98 102 ...  26  26  19]
 ...
 [ 63  90  90 ...  96  90  54]
 [ 55  85  87 ...  95  92  59]
 [ 37  59  61 ...  63  63  41]]
MASKED= [[45 66 71 ... 20

Number of columns =  307200
Lowval:  124
Highval:  242
100
190
low mask= [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True False False ... False False  True]
 [ True False False ... False False  True]
 [ True False  True ... False False  True]]
MASKED= [[-- 162 158 ... 158 156 --]
 [139 234 232 ... 242 237 138]
 [140 237 235 ... 236 231 139]
 ...
 [-- 193 179 ... 217 207 --]
 [-- 188 176 ... 216 205 --]
 [-- 125 -- ... 135 132 --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True False False ... False False  True]
 [ True False False ... False False  True]
 [ True False  True ... False False  True]] 
Matrix-> [[124 162 158 ... 158 156 124]
 [139 234 232 ... 242 237 138]
 [140 237 235 ... 236 231 139]
 ...
 [124 193 179 ... 217 207 124]
 [124 188 176 ... 216 205 124]
 [124 125 124 ... 135 132 1

Number of columns =  307200
Lowval:  0
Highval:  162
0
2
low mask= [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
MASKED= [[43 66 71 ... 19 19 17]
 [65 100 103 ... 25 29 20]
 [67 101 101 ... 23 28 20]
 ...
 [50 71 83 ... 93 83 59]
 [47 76 79 ... 91 82 55]
 [39 54 57 ... 58 63 36]]
Low MASK-> [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]] 
Matrix-> [[ 43  66  71 ...  19  19  17]
 [ 65 100 103 ...  25  29  20]
 [ 67 101 101 ...  23  28  20]
 ...
 [ 50  71  83 ...  93  83  59]
 [ 47  76  79 ...  91  82  55]
 [ 39  54  57 ...  58  63  36]]
MASKED= [[43 66 71 ... 1

Number of columns =  307200
Lowval:  121
Highval:  242
94
190
low mask= [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False  True]
 [False False False ... False False  True]
 [ True False False ... False False  True]]
MASKED= [[-- 162 158 ... 154 154 --]
 [139 232 232 ... 239 235 137]
 [140 235 233 ... 233 229 138]
 ...
 [123 222 220 ... 193 193 --]
 [124 217 219 ... 180 189 --]
 [-- 149 150 ... 123 123 --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False  True]
 [False False False ... False False  True]
 [ True False False ... False False  True]] 
Matrix-> [[121 162 158 ... 154 154 121]
 [139 232 232 ... 239 235 137]
 [140 235 233 ... 233 229 138]
 ...
 [123 222 220 ... 193 193 121]
 [124 217 219 ... 180 189 121]
 [121 149 150 ... 123 123

Number of columns =  307200
Lowval:  83
Highval:  245
68
122
low mask= [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [ True False False ... False False  True]]
MASKED= [[-- 131 129 ... 95 95 --]
 [118 193 191 ... 139 139 84]
 [114 194 194 ... 142 141 84]
 ...
 [114 190 189 ... 173 172 104]
 [111 185 185 ... 170 164 98]
 [-- 128 126 ... 109 113 --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [ True False False ... False False  True]] 
Matrix-> [[ 83 131 129 ...  95  95  83]
 [118 193 191 ... 139 139  84]
 [114 194 194 ... 142 141  84]
 ...
 [114 190 189 ... 173 172 104]
 [111 185 185 ... 170 164  98]
 [ 83 128 126 ... 109 113  83

shape of image =  3
HALF PERCENT-> 0.005
Channels->
 [array([[ 87, 162, 158, ..., 156, 156,  90],
       [139, 232, 232, ..., 238, 235, 136],
       [140, 235, 233, ..., 234, 229, 138],
       ...,
       [140, 237, 238, ..., 212, 188, 112],
       [146, 230, 234, ..., 214, 190, 115],
       [ 96, 159, 160, ..., 141, 135,  75]], dtype=uint8), array([[ 78, 131, 129, ...,  97,  97,  57],
       [118, 193, 191, ..., 139, 140,  85],
       [114, 194, 194, ..., 143, 142,  84],
       ...,
       [126, 222, 228, ..., 173, 154,  97],
       [130, 216, 227, ..., 180, 156,  96],
       [ 82, 147, 147, ..., 115, 112,  63]], dtype=uint8), array([[ 43,  66,  71, ...,  22,  22,  19],
       [ 65,  98, 101, ...,  26,  31,  20],
       [ 67,  99,  99, ...,  25,  29,  22],
       ...,
       [ 64, 114, 118, ...,  96,  81,  59],
       [ 67, 109, 112, ...,  92,  80,  63],
       [ 42,  72,  75, ...,  65,  64,  41]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [ 87 162 15

Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False  True]
 [False False False ... False False  True]
 [ True False False ... False False  True]] 
Matrix-> [[120 163 159 ... 156 156 120]
 [140 232 232 ... 238 235 136]
 [141 234 233 ... 234 229 138]
 ...
 [141 233 236 ... 194 202 120]
 [139 233 238 ... 192 196 120]
 [120 153 159 ... 126 132 120]]
MASKED= [[120 163 159 ... 156 156 120]
 [140 232 232 ... 238 235 136]
 [141 234 233 ... 234 229 138]
 ...
 [141 233 236 ... 194 202 120]
 [139 233 238 ... 192 196 120]
 [120 153 159 ... 126 132 120]]
vec= 307200 
Flat= [ 76 130 128 ... 106 115  65]
Number of columns =  307200
Lowval:  82
Highval:  245
68
122
low mask= [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... Fa

vec= 307200 
Flat= [43 66 70 ... 63 65 40]
Number of columns =  307200
Lowval:  0
Highval:  168
0
2
low mask= [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
MASKED= [[43 66 70 ... 22 22 19]
 [65 96 99 ... 26 31 20]
 [66 96 96 ... 25 29 22]
 ...
 [100 151 147 ... 95 103 59]
 [99 159 143 ... 74 101 65]
 [65 100 92 ... 63 65 40]]
Low MASK-> [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]] 
Matrix-> [[ 43  66  70 ...  22  22  19]
 [ 65  96  99 ...  26  31  20]
 [ 66  96  96 ...  25  29  22]
 ...
 [100 151 147 ...  95 103  59]
 [ 99 159 143 ...  74 101  65]
 [ 65 100

shape of image =  3
HALF PERCENT-> 0.005
Channels->
 [array([[ 91, 165, 161, ..., 154, 154,  88],
       [142, 234, 234, ..., 236, 233, 134],
       [143, 235, 233, ..., 231, 227, 136],
       ...,
       [142, 233, 241, ..., 193, 177, 111],
       [146, 236, 244, ..., 198, 187, 123],
       [ 96, 159, 164, ..., 135, 133,  79]], dtype=uint8), array([[ 74, 126, 124, ...,  97,  97,  58],
       [113, 187, 186, ..., 140, 141,  85],
       [109, 186, 186, ..., 145, 143,  85],
       ...,
       [141, 239, 243, ..., 165, 153,  94],
       [138, 237, 243, ..., 173, 164, 102],
       [ 88, 158, 158, ..., 111, 113,  73]], dtype=uint8), array([[ 43,  65,  69, ...,  21,  21,  18],
       [ 63,  95,  98, ...,  24,  29,  19],
       [ 65,  94,  94, ...,  23,  28,  20],
       ...,
       [ 87, 145, 153, ..., 101,  88,  62],
       [ 80, 144, 150, ..., 104,  97,  69],
       [ 50,  92,  98, ...,  72,  69,  42]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [ 91 165 16

MASKED= [[81 127 125 ... 95 95 81]
 [114 188 186 ... 139 140 85]
 [110 187 187 ... 144 142 85]
 ...
 [138 237 240 ... 162 148 86]
 [133 230 232 ... 174 164 100]
 [88 151 149 ... 114 115 81]]
vec= 307200 
Flat= [41 63 68 ... 72 71 45]
Number of columns =  307200
Lowval:  0
Highval:  165
0
2
low mask= [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
MASKED= [[41 63 68 ... 19 19 18]
 [62 94 97 ... 23 28 19]
 [64 93 93 ... 22 27 20]
 ...
 [88 138 143 ... 96 85 59]
 [78 131 132 ... 103 97 71]
 [57 84 85 ... 72 71 45]]
Low MASK-> [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False

shape of image =  3
HALF PERCENT-> 0.005
Channels->
 [array([[ 91, 163, 159, ..., 153, 153,  89],
       [142, 234, 234, ..., 236, 233, 135],
       [142, 235, 233, ..., 233, 229, 138],
       ...,
       [145, 240, 229, ..., 195, 186, 106],
       [144, 241, 224, ..., 193, 187, 119],
       [ 94, 165, 159, ..., 135, 138,  76]], dtype=uint8), array([[ 75, 125, 123, ...,  94,  94,  57],
       [114, 188, 186, ..., 138, 139,  84],
       [109, 187, 187, ..., 143, 142,  85],
       ...,
       [148, 232, 206, ..., 164, 153,  88],
       [146, 233, 208, ..., 170, 162, 103],
       [ 95, 157, 150, ..., 116, 120,  79]], dtype=uint8), array([[ 41,  61,  66, ...,  18,  18,  17],
       [ 62,  94,  97, ...,  22,  27,  18],
       [ 63,  93,  93, ...,  22,  27,  20],
       ...,
       [ 91, 132, 110, ...,  91,  84,  56],
       [ 84, 133, 106, ...,  95,  92,  69],
       [ 58,  87,  81, ...,  69,  71,  47]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [ 91 163 15

MASKED= [[119 163 159 ... 153 153 119]
 [142 234 234 ... 236 233 135]
 [142 235 233 ... 232 227 137]
 ...
 [134 227 237 ... 188 179 119]
 [137 237 235 ... 191 199 119]
 [119 158 156 ... 140 142 119]]
vec= 307200 
Flat= [ 75 125 123 ... 121 122  71]
Number of columns =  307200
Lowval:  81
Highval:  244
67
121
low mask= [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False  True]]
MASKED= [[-- 125 123 ... 94 94 --]
 [114 188 186 ... 138 139 84]
 [109 187 187 ... 142 141 84]
 ...
 [119 199 203 ... 155 143 86]
 [124 206 201 ... 166 172 94]
 [84 139 136 ... 121 122 --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False Fa

vec= 307200 
Flat= [43 64 69 ... 65 74 39]
Number of columns =  307200
Lowval:  0
Highval:  157
0
2
low mask= [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
MASKED= [[43 64 69 ... 18 18 16]
 [63 95 99 ... 19 25 16]
 [65 95 95 ... 20 25 19]
 ...
 [58 94 86 ... 90 78 62]
 [58 98 84 ... 87 82 60]
 [44 62 55 ... 65 74 39]]
Low MASK-> [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]] 
Matrix-> [[43 64 69 ... 18 18 16]
 [63 95 99 ... 19 25 16]
 [65 95 95 ... 20 25 19]
 ...
 [58 94 86 ... 90 78 62]
 [58 98 84 ... 87 82 60]
 [44 62 55 ... 65 74 39]]
MASKED= [[43 64 69 ..

Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [ True False False ... False False  True]] 
Matrix-> [[ 82 129 126 ...  94  94  82]
 [115 190 189 ... 135 136  82]
 [113 190 191 ... 141 140  83]
 ...
 [120 201 210 ... 191 154  87]
 [118 194 200 ... 172 146  82]
 [ 82 131 129 ... 107  94  82]]
MASKED= [[82 129 126 ... 94 94 82]
 [115 190 189 ... 135 136 82]
 [113 190 191 ... 141 140 83]
 ...
 [120 201 210 ... 191 154 87]
 [118 194 200 ... 172 146 82]
 [82 131 129 ... 107 94 82]]
vec= 307200 
Flat= [43 64 69 ... 55 51 37]
Number of columns =  307200
Lowval:  0
Highval:  155
0
2
low mask= [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [Fa

shape of image =  3
HALF PERCENT-> 0.005
Channels->
 [array([[ 95, 160, 156, ..., 150, 154,  88],
       [140, 230, 230, ..., 234, 234, 135],
       [141, 234, 234, ..., 234, 234, 140],
       ...,
       [135, 182, 136, ..., 199, 188, 102],
       [135, 194, 156, ..., 190, 170,  96],
       [ 92, 133, 115, ..., 115, 101,  55]], dtype=uint8), array([[ 79, 128, 128, ...,  94,  94,  53],
       [115, 190, 190, ..., 138, 138,  83],
       [114, 190, 192, ..., 138, 138,  81],
       ...,
       [118, 176, 131, ..., 152, 147,  87],
       [118, 181, 147, ..., 141, 130,  76],
       [ 73, 121, 107, ...,  89,  82,  48]], dtype=uint8), array([[ 43,  66,  67, ...,  18,  16,  14],
       [ 60,  97,  97, ...,  22,  22,  14],
       [ 64,  97,  94, ...,  20,  20,  16],
       ...,
       [ 72, 119,  85, ...,  83,  85,  55],
       [ 66, 122,  97, ...,  83,  86,  52],
       [ 38,  75,  75, ...,  57,  56,  33]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [ 95 160 15

Number of columns =  307200
Lowval:  119
Highval:  242
85
192
low mask= [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True False False ... False False False]
 [ True False False ... False False False]
 [ True False False ...  True  True  True]]
MASKED= [[-- 160 156 ... 150 154 --]
 [140 230 230 ... 234 234 135]
 [141 234 234 ... 234 234 140]
 ...
 [-- 173 176 ... 209 214 129]
 [-- 195 183 ... 185 181 125]
 [-- 136 125 ... -- -- --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True False False ... False False False]
 [ True False False ... False False False]
 [ True False False ...  True  True  True]] 
Matrix-> [[119 160 156 ... 150 154 119]
 [140 230 230 ... 234 234 135]
 [141 234 234 ... 234 234 140]
 ...
 [119 173 176 ... 209 214 129]
 [119 195 183 ... 185 181 125]
 [119 136 125 ... 119 119 1

 [-- 128 -- ... 143 151 --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True False False ... False False False]
 [ True False False ... False False False]
 [ True False  True ... False False  True]] 
Matrix-> [[119 161 157 ... 150 154 119]
 [142 231 231 ... 234 233 137]
 [142 236 236 ... 234 234 140]
 ...
 [119 171 161 ... 222 222 143]
 [119 179 158 ... 220 226 138]
 [119 128 119 ... 143 151 119]]
MASKED= [[119 161 157 ... 150 154 119]
 [142 231 231 ... 234 233 137]
 [142 236 236 ... 234 234 140]
 ...
 [119 171 161 ... 222 222 143]
 [119 179 158 ... 220 226 138]
 [119 128 119 ... 143 151 119]]
vec= 307200 
Flat= [ 78 127 127 ... 122 126  81]
Number of columns =  307200
Lowval:  81
Highval:  243
66
122
low mask= [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False Fals

MASKED= [[-- 160 156 ... 150 155 --]
 [140 230 232 ... 233 233 136]
 [141 233 233 ... 232 232 140]
 ...
 [-- 143 121 ... 237 241 136]
 [-- 158 134 ... 238 242 136]
 [-- -- -- ... 158 154 --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True False False ... False False False]
 [ True False False ... False False False]
 [ True  True  True ... False False  True]] 
Matrix-> [[120 160 156 ... 150 155 120]
 [140 230 232 ... 233 233 136]
 [141 233 233 ... 232 232 140]
 ...
 [120 143 121 ... 237 241 136]
 [120 158 134 ... 238 242 136]
 [120 120 120 ... 158 154 120]]
MASKED= [[120 160 156 ... 150 155 120]
 [140 230 232 ... 233 233 136]
 [141 233 233 ... 232 232 140]
 ...
 [120 143 121 ... 237 241 136]
 [120 158 134 ... 238 242 136]
 [120 120 120 ... 158 154 120]]
vec= 307200 
Flat= [ 75 126 126 ... 149 148  91]
Number of columns =  307200
Lowval:  82
Highval:  244
62
123
low mask= [[ True Fal

Number of columns =  307200
Lowval:  82
Highval:  244
61
123
low mask= [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True  True False ... False False False]
 [ True False False ... False False False]
 [ True  True  True ... False False False]]
MASKED= [[-- 125 125 ... 96 96 --]
 [114 187 187 ... 141 142 86]
 [113 186 188 ... 142 142 83]
 ...
 [-- -- 85 ... 218 220 139]
 [-- 83 82 ... 211 219 139]
 [-- -- -- ... 151 152 97]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True  True False ... False False False]
 [ True False False ... False False False]
 [ True  True  True ... False False False]] 
Matrix-> [[ 82 125 125 ...  96  96  82]
 [114 187 187 ... 141 142  86]
 [113 186 188 ... 142 142  83]
 ...
 [ 82  82  85 ... 218 220 139]
 [ 82  83  82 ... 211 219 139]
 [ 82  82  82 ... 151 152  97]]
MASK

MASKED= [[40 63 64 ... 20 17 16]
 [59 94 93 ... 24 25 17]
 [62 93 89 ... 23 23 18]
 ...
 [29 55 55 ... 111 117 82]
 [29 55 58 ... 109 123 81]
 [21 35 36 ... 77 85 53]]
Low MASK-> [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]] 
Matrix-> [[ 40  63  64 ...  20  17  16]
 [ 59  94  93 ...  24  25  17]
 [ 62  93  89 ...  23  23  18]
 ...
 [ 29  55  55 ... 111 117  82]
 [ 29  55  58 ... 109 123  81]
 [ 21  35  36 ...  77  85  53]]
MASKED= [[40 63 64 ... 20 17 16]
 [59 94 93 ... 24 25 17]
 [62 93 89 ... 23 23 18]
 ...
 [29 55 55 ... 111 117 82]
 [29 55 58 ... 109 123 81]
 [21 35 36 ... 77 85 53]]
shape of image =  3
HALF PERCENT-> 0.005
Channels->
 [array([[ 96, 161, 157, ..., 150, 154,  88],
       [143, 231, 232, ..., 233, 234, 136],
       [143, 234, 233, ..., 234, 234, 140],
 

Number of columns =  307200
Lowval:  123
Highval:  242
84
197
low mask= [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True  True False ... False False False]
 [ True  True  True ... False False False]
 [ True  True  True ... False False  True]]
MASKED= [[-- 161 157 ... 150 154 --]
 [143 231 232 ... 235 236 138]
 [143 234 233 ... 234 234 140]
 ...
 [-- -- 124 ... 240 236 148]
 [-- -- -- ... 236 234 144]
 [-- -- -- ... 153 154 --]]
Low MASK-> [[ True False False ... False False  True]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [ True  True False ... False False False]
 [ True  True  True ... False False False]
 [ True  True  True ... False False  True]] 
Matrix-> [[123 161 157 ... 150 154 123]
 [143 231 232 ... 235 236 138]
 [143 234 233 ... 234 234 140]
 ...
 [123 123 124 ... 240 236 148]
 [123 123 123 ... 236 234 144]
 [123 123 123 ... 153 154 123]

MASKED= [[82 124 123 ... 94 94 82]
 [113 186 185 ... 139 140 86]
 [110 184 186 ... 139 139 82]
 ...
 [82 82 82 ... 222 200 88]
 [82 82 82 ... 208 183 82]
 [82 82 82 ... 137 117 82]]
vec= 307200 
Flat= [40 62 63 ... 67 49 29]
Number of columns =  307200
Lowval:  0
Highval:  164
0
1
low mask= [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]
MASKED= [[40 62 63 ... 18 16 16]
 [59 93 93 ... 23 24 17]
 [61 92 89 ... 21 21 16]
 ...
 [39 58 56 ... 116 99 35]
 [45 56 55 ... 102 80 36]
 [30 38 32 ... 67 49 29]]
Low MASK-> [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]] 
Ma

shape of image =  3
HALF PERCENT-> 0.005
Channels->
 [array([[ 96, 160, 156, ..., 151, 156,  91],
       [143, 230, 232, ..., 235, 235, 137],
       [143, 235, 235, ..., 234, 234, 140],
       ...,
       [ 66, 114, 115, ..., 246, 221, 106],
       [ 66, 111, 116, ..., 236, 212,  98],
       [ 42,  74,  78, ..., 148, 135,  64]], dtype=uint8), array([[ 75, 124, 123, ...,  94,  96,  56],
       [113, 186, 185, ..., 139, 139,  85],
       [111, 186, 188, ..., 138, 138,  81],
       ...,
       [ 50,  82,  83, ..., 188, 145,  80],
       [ 51,  81,  81, ..., 164, 138,  74],
       [ 34,  53,  53, ..., 108,  94,  49]], dtype=uint8), array([[40, 62, 63, ..., 19, 17, 17],
       [59, 93, 93, ..., 23, 23, 16],
       [62, 94, 91, ..., 20, 20, 16],
       ...,
       [32, 60, 61, ..., 81, 40, 51],
       [33, 59, 60, ..., 65, 52, 52],
       [24, 39, 37, ..., 37, 38, 31]], dtype=uint8)]
Shape-> (480, 640)
Shape of channels-> 480
vec= 307200 
Flat= [ 96 160 156 ... 148 135  64]
Number of columns